"""ADK Skill definition + source-expandable REPL exports: Polya T1 Workflow-First 3-Layer topology.

Defines ``POLYA_UNDERSTAND_T1_WORKFLOW_SKILL`` using ``google.adk.skills.models.Skill``
and provides ``build_polya_understand_t1_workflow_skill_instruction_block()`` which
returns the XML discovery block + usage instructions to append to the reasoning
agent's ``static_instruction``.

Also registers source-expandable exports at import time so
``from rlm_repl_skills.polya_understand_t1_workflow import run_polya_understand_t1_workflow``
expands into inline source before the AST rewriter runs.

T1 Workflow-First 3-Layer Architecture:

  L0 (parent): sees manifest only -> generates workflow steps -> dispatches step assessors -> synthesizes
  L1 (step assessors): each gets one step + context packets -> assesses sufficiency -> optionally dispatches L2
  L2 (chunk assessors, conditional): each gets one chunk + step -> returns PRESENT/ABSENT/RELEVANCE
"""

from __future__ import annotations

import textwrap

from google.adk.skills.models import Frontmatter, Skill
from google.adk.skills.prompt import format_skills_as_xml

from rlm_adk.repl.skill_registry import ReplSkillExport, register_skill_export

# ===========================================================================
# ADK Skill definition (prompt discovery)
# ===========================================================================

POLYA_UNDERSTAND_T1_WORKFLOW_SKILL = Skill(
    frontmatter=Frontmatter(
        name="polya-understand-t1-workflow",
        description=(
            "Workflow-first 3-layer Polya understand topology. L0 generates "
            "workflow steps from the manifest, L1 step-assessors evaluate "
            "sufficiency per step with optional L2 chunk-level dispatch, and "
            "a final synthesis produces the composite understanding with gap "
            "assessment and retrieval order."
        ),
    ),
    instructions=textwrap.dedent("""\
## polya-understand-t1-workflow -- Workflow-First 3-Layer Context Validation

Use this source-expandable REPL skill when a project is large, messy, or
missing key context. It runs a workflow-first Polya understanding topology
that generates explicit workflow steps, assesses each step against the
available context, optionally drills into chunk-level assessment, and
synthesizes a composite understanding with gap analysis.

This is a **3-layer topology** (L0/L1/L2) designed for structured context
validation before planning or implementation.

### Usage

```repl
from rlm_repl_skills.polya_understand_t1_workflow import run_polya_understand_t1_workflow
result = run_polya_understand_t1_workflow(
    objective="Understand this project before planning any implementation work.",
    project_context=user_ctx,
    project_name="example-project",
)
print(result)
print(result.retrieval_order)
print(result.gap_assessment)
```

### Parameters

- ``objective`` (str): The concrete objective you are trying to understand.
- ``project_context`` (str | list | dict): The currently available context.
  Can be a packed repo XML string, repomix shards, notes, manifests, or a
  filename-to-content mapping (typically ``user_ctx``).
- ``project_name`` (str, default ``"project"``): Friendly label used in prompts.
- ``max_steps`` (int, default 8): Maximum workflow steps L0 can generate.
- ``max_chars_per_packet`` (int, default 12000): Chunk size for large context.
- ``max_packets`` (int, default 10): Caps how many packets are analyzed.
- ``max_retrievals`` (int, default 8): Caps extracted retrieval-order items.
- ``l2_threshold`` (int, default 4): If packet count exceeds this, L1 dispatches L2.
- ``emit_debug`` (bool, default True): Print debug logs to stdout.

### Return Value

``T1WorkflowResult`` with attributes:
- ``.understanding``: The synthesized understand-phase artifact.
- ``.workflow_steps``: List of workflow step strings generated by L0.
- ``.step_assessments``: List of ``T1StepAssessment`` objects from L1.
- ``.chunk_assessments``: Dict mapping step_idx -> list of ``T1ChunkAssessment``.
- ``.gap_assessment``: Extracted gap/missing-prerequisite summary.
- ``.retrieval_order``: Ordered list of missing prerequisite artifact names.
- ``.used_l2``: Whether L2 chunk-level dispatch was triggered.
- ``.debug_log``: List of debug messages.

### How It Works

**Layer 0 (Parent -- Workflow Generation):**
The parent sees only the manifest (file list + sizes) and generates a
numbered list of workflow steps needed to validate the objective.

**Layer 1 (Step Assessors -- dispatched via llm_query_batched):**
Each step assessor receives one workflow step plus the full set of
context packets and produces a structured assessment with STATUS
(SUFFICIENT/PARTIAL/MISSING), EVIDENCE, GAPS, and L2_DISPATCH flag.

**Layer 2 (Chunk Assessors -- conditional, via llm_query_batched):**
When L1 signals L2_DISPATCH: YES (or when packet count exceeds the
l2_threshold), each chunk is individually assessed against the step
with CHUNK_STATUS (PRESENT/ABSENT), RELEVANCE score, and SUMMARY.

**Final Synthesis:**
A synthesis prompt combines all assessments into a unified understanding
artifact with gap analysis and ordered retrieval plan.
"""),
)


def build_polya_understand_t1_workflow_skill_instruction_block() -> str:
    """Return the skill discovery XML + full instructions for prompt injection."""
    discovery_xml = format_skills_as_xml([POLYA_UNDERSTAND_T1_WORKFLOW_SKILL.frontmatter])
    return f"\n{discovery_xml}\n{POLYA_UNDERSTAND_T1_WORKFLOW_SKILL.instructions}"


# ===========================================================================
# Source-expandable REPL exports (side-effect registration at import time)
# ===========================================================================

# ---------------------------------------------------------------------------
# Constants: Instruction prompts
# ---------------------------------------------------------------------------

_T1_WORKFLOW_INSTRUCTIONS_SRC = """\
T1_WORKFLOW_INSTRUCTIONS = (
    "You are executing the WORKFLOW GENERATION phase (L0) of a Polya "
    "understand loop using the T1 Workflow-First 3-Layer topology. "
    "You receive ONLY a manifest (file list with sizes) -- NOT the raw context. "
    "Your task: generate a numbered list of concrete workflow steps needed to "
    "validate whether the available context is sufficient for the given objective. "
    "Each step should be a specific validation action (e.g., 'Verify that API "
    "authentication credentials are documented', 'Check that database schema "
    "definitions are present'). "
    "Do NOT answer the questions or assess sufficiency yourself. "
    "Do NOT hallucinate file contents. "
    "Return ONLY a numbered list of steps, one per line, in the format: "
    "1. <step description>"
)\
"""

_T1_ASSESS_INSTRUCTIONS_SRC = """\
T1_ASSESS_INSTRUCTIONS = (
    "You are executing the STEP ASSESSMENT phase (L1) of a Polya "
    "understand loop using the T1 Workflow-First 3-Layer topology. "
    "You receive one workflow step and the available context packets. "
    "Assess whether the context is sufficient to complete this step. "
    "Return your assessment using these exact markers, each on its own line: "
    "STATUS: SUFFICIENT | PARTIAL | MISSING "
    "EVIDENCE: <specific evidence from the context supporting this step> "
    "GAPS: <specific information missing for this step, or NONE> "
    "L2_DISPATCH: YES | NO (YES if chunk-level analysis would help clarify)"
)\
"""

# ---------------------------------------------------------------------------
# Result classes
# ---------------------------------------------------------------------------

_T1_STEP_ASSESSMENT_SRC = """\
class T1StepAssessment:
    def __init__(self, step_description, status, evidence, gaps, chunk_assessments=None, raw_response=""):
        self.step_description = step_description
        self.status = status
        self.evidence = evidence
        self.gaps = gaps
        self.chunk_assessments = chunk_assessments or []
        self.raw_response = raw_response

    def __repr__(self):
        return (
            "T1StepAssessment(status=" + repr(self.status)
            + ", gaps=" + repr(self.gaps[:60] if self.gaps else "")
            + ", n_chunks=" + str(len(self.chunk_assessments)) + ")"
        )\
"""

_T1_CHUNK_ASSESSMENT_SRC = """\
class T1ChunkAssessment:
    def __init__(self, chunk_id, status, relevance_score, summary, raw_response=""):
        self.chunk_id = chunk_id
        self.status = status
        self.relevance_score = relevance_score
        self.summary = summary
        self.raw_response = raw_response

    def __repr__(self):
        return (
            "T1ChunkAssessment(chunk_id=" + repr(self.chunk_id)
            + ", status=" + repr(self.status)
            + ", relevance=" + str(self.relevance_score) + ")"
        )\
"""

_T1_WORKFLOW_RESULT_SRC = """\
class T1WorkflowResult:
    def __init__(
        self,
        understanding,
        workflow_steps,
        step_assessments,
        chunk_assessments,
        gap_assessment,
        retrieval_order,
        used_l2,
        debug_log=None,
    ):
        self.understanding = understanding
        self.workflow_steps = workflow_steps
        self.step_assessments = step_assessments
        self.chunk_assessments = chunk_assessments
        self.gap_assessment = gap_assessment
        self.retrieval_order = retrieval_order
        self.used_l2 = used_l2
        self.debug_log = debug_log or []

    def __repr__(self):
        return (
            "T1WorkflowResult(steps=" + str(len(self.workflow_steps))
            + ", assessments=" + str(len(self.step_assessments))
            + ", used_l2=" + str(self.used_l2)
            + ", retrievals=" + str(len(self.retrieval_order)) + ")"
        )\
"""

# ---------------------------------------------------------------------------
# Helpers: context preparation, manifest building, and extraction
# (copied from v1 polya_understand for self-contained expansion)
# ---------------------------------------------------------------------------

_STRINGIFY_CONTEXT_SRC = """\
def stringify_context(value, heading="context"):
    if value is None:
        return ""
    if isinstance(value, str):
        return value
    if isinstance(value, dict):
        pieces = []
        keys = sorted(value.keys(), key=lambda item: str(item))
        for key in keys:
            rendered = stringify_context(value[key], str(key))
            pieces.append("[[" + str(key) + "]]\\n" + rendered)
        return "\\n\\n".join(pieces)
    if isinstance(value, (list, tuple)):
        pieces = []
        for idx, item in enumerate(value):
            rendered = stringify_context(item, heading + "_" + str(idx + 1))
            pieces.append("[[item_" + str(idx + 1) + "]]\\n" + rendered)
        return "\\n\\n".join(pieces)
    return repr(value)\
"""

_CHUNK_TEXT_SRC = """\
def chunk_text(text, max_chars=12000):
    text = str(text or "")
    if not text:
        return [""]
    if len(text) <= max_chars:
        return [text]
    chunks = []
    cursor = 0
    min_cut = int(max_chars * 0.5)
    while cursor < len(text):
        end = min(len(text), cursor + max_chars)
        cut = end
        if end < len(text):
            split_at = text.rfind("\\n\\n", cursor, end)
            if split_at < cursor + min_cut:
                split_at = text.rfind("\\n", cursor, end)
            if split_at >= cursor + min_cut:
                cut = split_at
        if cut <= cursor:
            cut = end
        piece = text[cursor:cut].strip()
        if piece:
            chunks.append(piece)
        cursor = cut
    return chunks or [text[:max_chars]]\
"""

_CONDENSE_PACKETS_SRC = """\
def condense_packets(packets, max_packets=10):
    if len(packets) <= max_packets:
        return packets
    group_size = (len(packets) + max_packets - 1) // max_packets
    condensed = []
    for start in range(0, len(packets), group_size):
        group = packets[start:start + group_size]
        header = (
            "[[merged_packets_" + str(start + 1)
            + "_to_" + str(start + len(group)) + "]]"
        )
        condensed.append(header + "\\n" + "\\n\\n-----\\n\\n".join(group))
    return condensed[:max_packets]\
"""

_PREPARE_CONTEXT_PACKETS_SRC = """\
def prepare_context_packets(project_context, max_chars_per_packet=12000, max_packets=10):
    packets = []
    if isinstance(project_context, dict):
        keys = sorted(project_context.keys(), key=lambda item: str(item))
        for key in keys:
            base = "[[" + str(key) + "]]\\n" + stringify_context(project_context[key], str(key))
            packets.extend(chunk_text(base, max_chars_per_packet))
    elif isinstance(project_context, (list, tuple)):
        for idx, item in enumerate(project_context):
            base = (
                "[[packet_" + str(idx + 1) + "]]\\n"
                + stringify_context(item, "packet_" + str(idx + 1))
            )
            packets.extend(chunk_text(base, max_chars_per_packet))
    else:
        base = stringify_context(project_context, "project_context")
        packets.extend(chunk_text(base, max_chars_per_packet))
    packets = [packet for packet in packets if str(packet).strip()]
    if not packets:
        packets = ["[[empty_context]]"]
    return condense_packets(packets, max_packets)\
"""

_BUILD_CONTEXT_MANIFEST_SRC = '''\
def build_context_manifest(project_context):
    """Build a lightweight manifest (file list + sizes) from project_context.

    The parent (L0) sees ONLY this manifest, never raw context.
    L1 step assessors see the actual context packets.
    """
    lines = []
    if isinstance(project_context, dict):
        keys = sorted(project_context.keys(), key=lambda item: str(item))
        for key in keys:
            content = project_context[key]
            size = len(str(content)) if content else 0
            lines.append("  - " + str(key) + " (" + str(size) + " chars)")
    elif isinstance(project_context, (list, tuple)):
        for idx, item in enumerate(project_context):
            size = len(str(item)) if item else 0
            lines.append("  - packet_" + str(idx + 1) + " (" + str(size) + " chars)")
    else:
        text = str(project_context or "")
        lines.append("  - raw_context (" + str(len(text)) + " chars)")
    header = "PROJECT CONTEXT MANIFEST (" + str(len(lines)) + " items):"
    return header + "\\n" + "\\n".join(lines)\
'''

_EXTRACT_RETRIEVAL_ORDER_SRC = """\
def extract_retrieval_order(text, max_items=8):
    lines = str(text or "").split("\\n")
    for header in ("REVISED_RETRIEVAL_ORDER", "RETRIEVAL_ORDER"):
        start_idx = None
        inline_value = ""
        for idx, line in enumerate(lines):
            stripped = line.strip()
            upper = stripped.upper()
            if upper == header + ":":
                start_idx = idx + 1
                break
            if upper.startswith(header + ":"):
                start_idx = idx + 1
                inline_value = stripped.split(":", 1)[1].strip()
                break
        items = []
        if inline_value:
            if inline_value.upper() == "NONE":
                return []
            candidate = inline_value.split("|", 1)[0].strip()
            if candidate:
                items.append(candidate)
        if start_idx is None:
            continue
        for line in lines[start_idx:]:
            stripped = line.strip()
            if not stripped:
                if items:
                    break
                continue
            upper = stripped.upper()
            if upper.endswith(":") and (
                stripped.replace("_", "").replace("-", "").replace(":", "").replace(" ", "").isupper()
            ):
                break
            candidate = stripped
            if candidate[:1] in "-*":
                candidate = candidate[1:].strip()
            else:
                pos = 0
                while pos < len(candidate) and candidate[pos].isdigit():
                    pos += 1
                if pos > 0 and pos < len(candidate) and candidate[pos] in ".)":
                    candidate = candidate[pos + 1:].strip()
            if not candidate:
                continue
            if candidate.upper() == "NONE":
                return []
            candidate = candidate.split("|", 1)[0].strip()
            if candidate and candidate not in items:
                items.append(candidate)
            if len(items) >= max_items:
                return items
        if items:
            return items
    return []\
"""

# ---------------------------------------------------------------------------
# T1-specific prompt builders
# ---------------------------------------------------------------------------

_BUILD_WORKFLOW_PROMPT_SRC = '''\
def build_workflow_prompt(objective, manifest, max_steps=8):
    """L0 prompt: generate workflow steps from manifest only.

    The parent sees ONLY the manifest (file list + sizes), never raw context.
    """
    parts = [T1_WORKFLOW_INSTRUCTIONS]
    parts.append("\\n\\nOBJECTIVE: " + str(objective))
    parts.append("\\n\\nCONTEXT_MANIFEST:\\n" + str(manifest))
    parts.append(
        "\\n\\nGenerate up to " + str(max_steps)
        + " concrete workflow steps to validate context sufficiency. "
        "Return ONLY a numbered list."
    )
    return "".join(parts)\
'''

_PARSE_WORKFLOW_STEPS_SRC = """\
def parse_workflow_steps(workflow_output, max_steps=8):
    raw = str(workflow_output or "").strip()
    if not raw:
        return []
    steps = []
    for line in raw.split("\\n"):
        stripped = line.strip()
        if not stripped:
            continue
        candidate = stripped
        # Strip numbered prefix: "1. ", "1) ", etc.
        pos = 0
        while pos < len(candidate) and candidate[pos].isdigit():
            pos += 1
        if pos > 0 and pos < len(candidate) and candidate[pos] in ".)":
            candidate = candidate[pos + 1:].strip()
        # Strip bullet prefix
        elif candidate[:1] in "-*":
            candidate = candidate[1:].strip()
        if candidate:
            steps.append(candidate)
        if len(steps) >= max_steps:
            break
    return steps\
"""

_BUILD_STEP_ASSESSMENT_PROMPT_SRC = '''\
def build_step_assessment_prompt(step, context_packets, manifest, step_idx, total_steps, use_l2=False):
    """L1 prompt: assess one workflow step against context packets."""
    parts = [T1_ASSESS_INSTRUCTIONS]
    parts.append("\\n\\nWORKFLOW STEP " + str(step_idx + 1) + "/" + str(total_steps) + ":")
    parts.append("\\n" + str(step))
    parts.append("\\n\\nCONTEXT_MANIFEST:\\n" + str(manifest))
    parts.append("\\n\\nCONTEXT_PACKETS:")
    for idx, packet in enumerate(context_packets):
        parts.append("\\n\\n[PACKET " + str(idx + 1) + "]:\\n" + str(packet))
    if use_l2:
        parts.append(
            "\\n\\nNOTE: If you cannot determine sufficiency from the packets, "
            "set L2_DISPATCH: YES to request chunk-level analysis."
        )
    parts.append("\\n\\nReturn your structured assessment now.")
    return "".join(parts)\
'''

_BUILD_CHUNK_ASSESSMENT_PROMPT_SRC = """\
def build_chunk_assessment_prompt(chunk, step, chunk_idx, total_chunks):
    parts = []
    parts.append(
        "You are executing CHUNK ASSESSMENT (L2) of a Polya understand loop. "
        "Assess whether this chunk contains information relevant to the given "
        "workflow step."
    )
    parts.append("\\n\\nWORKFLOW STEP: " + str(step))
    parts.append("\\n\\nCHUNK " + str(chunk_idx + 1) + "/" + str(total_chunks) + ":")
    parts.append("\\n" + str(chunk))
    parts.append(
        "\\n\\nReturn your assessment using these exact markers, each on its own line: "
        "CHUNK_STATUS: PRESENT | ABSENT "
        "RELEVANCE: <float 0.0 to 1.0> "
        "SUMMARY: <one-line summary of relevant content, or NONE>"
    )
    return "".join(parts)\
"""

_PARSE_STEP_ASSESSMENT_SRC = """\
def parse_step_assessment(response_text, step_description):
    text = str(response_text or "")
    status = "MISSING"
    evidence = ""
    gaps = ""
    l2_dispatch = False
    for line in text.split("\\n"):
        stripped = line.strip()
        upper = stripped.upper()
        if upper.startswith("STATUS:"):
            val = stripped.split(":", 1)[1].strip().upper()
            if val in ("SUFFICIENT", "PARTIAL", "MISSING"):
                status = val
        elif upper.startswith("EVIDENCE:"):
            evidence = stripped.split(":", 1)[1].strip()
        elif upper.startswith("GAPS:"):
            gaps = stripped.split(":", 1)[1].strip()
        elif upper.startswith("L2_DISPATCH:"):
            val = stripped.split(":", 1)[1].strip().upper()
            l2_dispatch = val == "YES"
    return T1StepAssessment(
        step_description=step_description,
        status=status,
        evidence=evidence,
        gaps=gaps,
        raw_response=text,
    ), l2_dispatch\
"""

_PARSE_CHUNK_ASSESSMENT_SRC = """\
def parse_chunk_assessment(response_text, chunk_id):
    text = str(response_text or "")
    status = "ABSENT"
    relevance_score = 0.0
    summary = ""
    for line in text.split("\\n"):
        stripped = line.strip()
        upper = stripped.upper()
        if upper.startswith("CHUNK_STATUS:"):
            val = stripped.split(":", 1)[1].strip().upper()
            if val in ("PRESENT", "ABSENT"):
                status = val
        elif upper.startswith("RELEVANCE:"):
            val = stripped.split(":", 1)[1].strip()
            try:
                relevance_score = float(val)
            except (ValueError, TypeError):
                relevance_score = 0.0
        elif upper.startswith("SUMMARY:"):
            summary = stripped.split(":", 1)[1].strip()
    return T1ChunkAssessment(
        chunk_id=chunk_id,
        status=status,
        relevance_score=relevance_score,
        summary=summary,
        raw_response=text,
    )\
"""

_NEEDS_L2_DISPATCH_SRC = """\
def needs_l2_dispatch(context_packets, threshold=4):
    return len(context_packets) > threshold\
"""

_BUILD_SYNTHESIS_PROMPT_SRC = '''\
def build_synthesis_prompt(
    objective,
    workflow_steps,
    step_assessments,
    chunk_assessments_by_step,
    manifest,
    used_l2,
):
    """Build the final synthesis prompt combining all assessments."""
    parts = []
    parts.append(
        "You are executing the SYNTHESIS phase of a Polya understand loop "
        "using the T1 Workflow-First 3-Layer topology. "
        "Combine the workflow step assessments (and optional chunk assessments) "
        "into a unified understanding artifact."
    )
    parts.append("\\n\\nOBJECTIVE: " + str(objective))
    parts.append("\\n\\nCONTEXT_MANIFEST:\\n" + str(manifest))
    parts.append("\\n\\nWORKFLOW STEPS AND ASSESSMENTS:")
    for idx, step in enumerate(workflow_steps):
        parts.append("\\n\\n--- Step " + str(idx + 1) + ": " + str(step) + " ---")
        if idx < len(step_assessments):
            sa = step_assessments[idx]
            parts.append("\\nSTATUS: " + str(sa.status))
            parts.append("\\nEVIDENCE: " + str(sa.evidence))
            parts.append("\\nGAPS: " + str(sa.gaps))
        chunk_list = chunk_assessments_by_step.get(idx, [])
        if chunk_list:
            parts.append("\\nCHUNK ASSESSMENTS:")
            for ca in chunk_list:
                parts.append(
                    "\\n  - " + str(ca.chunk_id)
                    + " [" + str(ca.status) + ", relevance="
                    + str(ca.relevance_score) + "]: " + str(ca.summary)
                )
    parts.append("\\n\\nUsed L2 chunk-level dispatch: " + str(used_l2))
    parts.append(
        "\\n\\nReturn the following structure: "
        "UNDERSTANDING: <composite understanding> "
        "GAP_ASSESSMENT: <summary of gaps across all steps> "
        "RETRIEVAL_ORDER: numbered list of missing items in dependency order, or NONE"
    )
    return "".join(parts)\
'''

# ---------------------------------------------------------------------------
# Main orchestrator function
# ---------------------------------------------------------------------------

_RUN_POLYA_UNDERSTAND_T1_WORKFLOW_SRC = '''\
def run_polya_understand_t1_workflow(
    objective,
    project_context,
    project_name="project",
    max_steps=8,
    max_chars_per_packet=12000,
    max_packets=10,
    max_retrievals=8,
    l2_threshold=4,
    emit_debug=True,
):
    """Run the T1 Workflow-First 3-Layer Polya understand topology.

    L0 generates workflow steps from the manifest.
    L1 assesses each step against context packets.
    L2 (conditional) does chunk-level assessment when packet count
    exceeds l2_threshold or L1 requests it.

    Args:
        objective: Concrete objective to validate.
        project_context: Context blob, shards, or manifest mapping.
        project_name: Friendly label for prompt context.
        max_steps: Maximum workflow steps L0 can generate.
        max_chars_per_packet: Packet size for chunking.
        max_packets: Maximum packet count after chunking/merging.
        max_retrievals: Maximum retrieval-order items.
        l2_threshold: Packet count threshold triggering L2.
        emit_debug: Whether to print debug logs.

    Returns:
        T1WorkflowResult with the synthesized understanding and
        ordered missing-context retrieval plan.
    """
    debug_log = []
    objective_text = (
        str(objective).strip()
        if str(objective).strip()
        else "Validate whether the current project context is sufficient to proceed."
    )

    def _log(msg):
        if emit_debug:
            print(msg)
        debug_log.append(msg)

    # --- Phase 0: Prepare context ---
    packets = prepare_context_packets(
        project_context,
        max_chars_per_packet=max_chars_per_packet,
        max_packets=max_packets,
    )
    manifest = build_context_manifest(project_context)
    _log(
        "[t1_workflow] Starting T1 workflow for "
        + project_name + " with " + str(len(packets)) + " packet(s)"
    )

    # --- Phase 1: L0 generates workflow steps ---
    _log("\\n[t1_workflow] Phase 1: L0 Workflow Generation")
    workflow_prompt = build_workflow_prompt(objective_text, manifest, max_steps)
    _log(
        "[t1_workflow] Dispatching workflow generation (prompt_len="
        + str(len(workflow_prompt)) + ")"
    )
    workflow_output = llm_query(workflow_prompt)
    workflow_steps = parse_workflow_steps(str(workflow_output), max_steps)
    _log(
        "[t1_workflow] Generated " + str(len(workflow_steps)) + " workflow step(s)"
    )
    if not workflow_steps:
        workflow_steps = ["Assess overall context sufficiency for: " + objective_text]
        _log("[t1_workflow] Fallback: using default single step")

    # --- Phase 2: L1 step assessment (batched) ---
    _log("\\n[t1_workflow] Phase 2: L1 Step Assessment")
    use_l2_flag = needs_l2_dispatch(packets, l2_threshold)
    assess_prompts = []
    for step_idx, step in enumerate(workflow_steps):
        assess_prompts.append(
            build_step_assessment_prompt(
                step, packets, manifest, step_idx, len(workflow_steps), use_l2_flag
            )
        )
    _log(
        "[t1_workflow] Dispatching " + str(len(assess_prompts))
        + " step assessor(s)"
    )
    assess_outputs = llm_query_batched(assess_prompts)
    step_assessments = []
    l2_requested_steps = []
    for step_idx, output in enumerate(assess_outputs):
        step_desc = workflow_steps[step_idx] if step_idx < len(workflow_steps) else ""
        assessment, wants_l2 = parse_step_assessment(str(output), step_desc)
        step_assessments.append(assessment)
        if wants_l2 or use_l2_flag:
            l2_requested_steps.append(step_idx)
    _log(
        "[t1_workflow] Received " + str(len(step_assessments))
        + " step assessment(s), " + str(len(l2_requested_steps))
        + " requesting L2"
    )

    # --- Phase 3 (conditional): L2 chunk assessment ---
    chunk_assessments_by_step = {}
    used_l2 = False
    if l2_requested_steps:
        _log("\\n[t1_workflow] Phase 3: L2 Chunk Assessment")
        used_l2 = True
        chunk_prompts = []
        chunk_prompt_keys = []  # (step_idx, chunk_idx) for reassembly
        for step_idx in l2_requested_steps:
            step = workflow_steps[step_idx] if step_idx < len(workflow_steps) else ""
            for chunk_idx, chunk in enumerate(packets):
                chunk_prompts.append(
                    build_chunk_assessment_prompt(
                        chunk, step, chunk_idx, len(packets)
                    )
                )
                chunk_prompt_keys.append((step_idx, chunk_idx))
        _log(
            "[t1_workflow] Dispatching " + str(len(chunk_prompts))
            + " chunk assessor(s)"
        )
        chunk_outputs = llm_query_batched(chunk_prompts)
        for key_idx, output in enumerate(chunk_outputs):
            step_idx, chunk_idx = chunk_prompt_keys[key_idx]
            chunk_id = "step_" + str(step_idx + 1) + "_chunk_" + str(chunk_idx + 1)
            ca = parse_chunk_assessment(str(output), chunk_id)
            chunk_assessments_by_step.setdefault(step_idx, []).append(ca)
            if step_idx < len(step_assessments):
                step_assessments[step_idx].chunk_assessments.append(ca)
        _log(
            "[t1_workflow] Received " + str(len(chunk_outputs))
            + " chunk assessment(s)"
        )
    else:
        _log("\\n[t1_workflow] Phase 3: L2 skipped (not needed)")

    # --- Phase 4: Synthesis ---
    _log("\\n[t1_workflow] Phase 4: Synthesis")
    synthesis_prompt = build_synthesis_prompt(
        objective_text,
        workflow_steps,
        step_assessments,
        chunk_assessments_by_step,
        manifest,
        used_l2,
    )
    _log(
        "[t1_workflow] Dispatching synthesis (prompt_len="
        + str(len(synthesis_prompt)) + ")"
    )
    synthesis_output = str(llm_query(synthesis_prompt))

    # Extract structured fields from synthesis (multi-line aware)
    def _extract_field(text, heading):
        heading_upper = heading.strip().upper()
        lines = text.split("\\n")
        for idx, line in enumerate(lines):
            stripped = line.strip()
            upper = stripped.upper()
            if upper.startswith(heading_upper + ":"):
                inline_value = stripped[len(heading_upper) + 1:].strip()
                section_lines = []
                for subsequent in lines[idx + 1:]:
                    sub_stripped = subsequent.strip()
                    if not sub_stripped:
                        if section_lines:
                            break
                        continue
                    if (
                        ":" in sub_stripped
                        and sub_stripped.split(":", 1)[0].replace("_", "").replace("-", "").replace(" ", "").isupper()
                        and len(sub_stripped.split(":", 1)[0].strip()) > 1
                    ):
                        break
                    section_lines.append(subsequent.rstrip())
                if section_lines:
                    if inline_value:
                        return inline_value + "\\n" + "\\n".join(section_lines)
                    return "\\n".join(section_lines)
                return inline_value
        return ""
    understanding = _extract_field(synthesis_output, "UNDERSTANDING")
    gap_assessment = _extract_field(synthesis_output, "GAP_ASSESSMENT")
    if not understanding:
        understanding = synthesis_output
    retrieval_order = extract_retrieval_order(synthesis_output, max_items=max_retrievals)

    _log(
        "[t1_workflow] Synthesis complete: "
        + str(len(retrieval_order)) + " retrieval candidate(s)"
    )

    return T1WorkflowResult(
        understanding=understanding,
        workflow_steps=workflow_steps,
        step_assessments=step_assessments,
        chunk_assessments=chunk_assessments_by_step,
        gap_assessment=gap_assessment,
        retrieval_order=retrieval_order,
        used_l2=used_l2,
        debug_log=debug_log,
    )\
'''

# ---------------------------------------------------------------------------
# Registration (side-effect at import time)
# ---------------------------------------------------------------------------

_MODULE = "rlm_repl_skills.polya_understand_t1_workflow"

register_skill_export(
    ReplSkillExport(
        module=_MODULE,
        name="T1_WORKFLOW_INSTRUCTIONS",
        source=_T1_WORKFLOW_INSTRUCTIONS_SRC,
        requires=[],
        kind="const",
    )
)

register_skill_export(
    ReplSkillExport(
        module=_MODULE,
        name="T1_ASSESS_INSTRUCTIONS",
        source=_T1_ASSESS_INSTRUCTIONS_SRC,
        requires=[],
        kind="const",
    )
)

register_skill_export(
    ReplSkillExport(
        module=_MODULE,
        name="T1StepAssessment",
        source=_T1_STEP_ASSESSMENT_SRC,
        requires=[],
        kind="class",
    )
)

register_skill_export(
    ReplSkillExport(
        module=_MODULE,
        name="T1ChunkAssessment",
        source=_T1_CHUNK_ASSESSMENT_SRC,
        requires=[],
        kind="class",
    )
)

register_skill_export(
    ReplSkillExport(
        module=_MODULE,
        name="T1WorkflowResult",
        source=_T1_WORKFLOW_RESULT_SRC,
        requires=[],
        kind="class",
    )
)

register_skill_export(
    ReplSkillExport(
        module=_MODULE,
        name="stringify_context",
        source=_STRINGIFY_CONTEXT_SRC,
        requires=[],
        kind="function",
    )
)

register_skill_export(
    ReplSkillExport(
        module=_MODULE,
        name="chunk_text",
        source=_CHUNK_TEXT_SRC,
        requires=[],
        kind="function",
    )
)

register_skill_export(
    ReplSkillExport(
        module=_MODULE,
        name="condense_packets",
        source=_CONDENSE_PACKETS_SRC,
        requires=[],
        kind="function",
    )
)

register_skill_export(
    ReplSkillExport(
        module=_MODULE,
        name="prepare_context_packets",
        source=_PREPARE_CONTEXT_PACKETS_SRC,
        requires=["stringify_context", "chunk_text", "condense_packets"],
        kind="function",
    )
)

register_skill_export(
    ReplSkillExport(
        module=_MODULE,
        name="build_context_manifest",
        source=_BUILD_CONTEXT_MANIFEST_SRC,
        requires=[],
        kind="function",
    )
)

register_skill_export(
    ReplSkillExport(
        module=_MODULE,
        name="extract_retrieval_order",
        source=_EXTRACT_RETRIEVAL_ORDER_SRC,
        requires=[],
        kind="function",
    )
)

register_skill_export(
    ReplSkillExport(
        module=_MODULE,
        name="build_workflow_prompt",
        source=_BUILD_WORKFLOW_PROMPT_SRC,
        requires=["T1_WORKFLOW_INSTRUCTIONS"],
        kind="function",
    )
)

register_skill_export(
    ReplSkillExport(
        module=_MODULE,
        name="parse_workflow_steps",
        source=_PARSE_WORKFLOW_STEPS_SRC,
        requires=[],
        kind="function",
    )
)

register_skill_export(
    ReplSkillExport(
        module=_MODULE,
        name="build_step_assessment_prompt",
        source=_BUILD_STEP_ASSESSMENT_PROMPT_SRC,
        requires=["T1_ASSESS_INSTRUCTIONS"],
        kind="function",
    )
)

register_skill_export(
    ReplSkillExport(
        module=_MODULE,
        name="build_chunk_assessment_prompt",
        source=_BUILD_CHUNK_ASSESSMENT_PROMPT_SRC,
        requires=[],
        kind="function",
    )
)

register_skill_export(
    ReplSkillExport(
        module=_MODULE,
        name="parse_step_assessment",
        source=_PARSE_STEP_ASSESSMENT_SRC,
        requires=["T1StepAssessment"],
        kind="function",
    )
)

register_skill_export(
    ReplSkillExport(
        module=_MODULE,
        name="parse_chunk_assessment",
        source=_PARSE_CHUNK_ASSESSMENT_SRC,
        requires=["T1ChunkAssessment"],
        kind="function",
    )
)

register_skill_export(
    ReplSkillExport(
        module=_MODULE,
        name="needs_l2_dispatch",
        source=_NEEDS_L2_DISPATCH_SRC,
        requires=[],
        kind="function",
    )
)

register_skill_export(
    ReplSkillExport(
        module=_MODULE,
        name="build_synthesis_prompt",
        source=_BUILD_SYNTHESIS_PROMPT_SRC,
        requires=[],
        kind="function",
    )
)

register_skill_export(
    ReplSkillExport(
        module=_MODULE,
        name="run_polya_understand_t1_workflow",
        source=_RUN_POLYA_UNDERSTAND_T1_WORKFLOW_SRC,
        requires=[
            "T1_WORKFLOW_INSTRUCTIONS",
            "T1_ASSESS_INSTRUCTIONS",
            "T1StepAssessment",
            "T1ChunkAssessment",
            "T1WorkflowResult",
            "prepare_context_packets",
            "build_context_manifest",
            "extract_retrieval_order",
            "build_workflow_prompt",
            "parse_workflow_steps",
            "build_step_assessment_prompt",
            "build_chunk_assessment_prompt",
            "parse_step_assessment",
            "parse_chunk_assessment",
            "needs_l2_dispatch",
            "build_synthesis_prompt",
        ],
        kind="function",
    )
)
